### ISSUE TITLE
use java 1_7

### ISSUE THREAD

**Issue by miladcoder** [arunkumar9t2/rxSuggestions#2]
dear developer
how can use in java_1.7 or below ?

**Comment by arunkumar9t2** [comment]
Hello, currently as I mentioned in the description I use 1.8 to take advantages of lambdas and try with resources. At the moment there is no plan to use 1.7.

If you would to use, please create a fork and use https://github.com/evant/gradle-retrolambda to retain lambda support in source code.

**Comment by arunkumar9t2** [comment]
Hi, Android Studio 3.0 reached stable and supports compilation with Java 1.8. At this time, there is no plan to compile with 1.7.

Closing the issue.
